# Generated by Django 5.2 on 2025-04-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcompletion',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcompletion',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
